# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/MyProjects/FPGA/test/test.srcs/sources_1/ip/c_shift_ram_32Wx1024D/c_shift_ram_32Wx1024D.xci
# IP: The module: 'c_shift_ram_32Wx1024D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyProjects/FPGA/test/test.srcs/sources_1/ip/c_shift_ram_32Wx1024D/c_shift_ram_32Wx1024D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_32Wx1024D'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/MyProjects/FPGA/test/test.srcs/sources_1/ip/c_shift_ram_32Wx1024D/c_shift_ram_32Wx1024D.xci
# IP: The module: 'c_shift_ram_32Wx1024D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/MyProjects/FPGA/test/test.srcs/sources_1/ip/c_shift_ram_32Wx1024D/c_shift_ram_32Wx1024D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_shift_ram_32Wx1024D'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
